version: 2.1
executors:
  build:
    docker:
      - image: circleci/golang:1.15

jobs:
  build:
    executor:
      name: build
    environment:
      TEST_RESULTS: /tmp/test-results
      TENANTCODE: dummy
      OBCID: 0
      PASSWORD: dummy
    working_directory: ~/app
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: linting
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6
            golangci-lint run
      - run: go get -u github.com/jstemmer/go-junit-report
      - run: |
          go test -v -race -cover -coverprofile=/tmp/cover.out -covermode=atomic ./... | go-junit-report -set-exit-code=true > ${TEST_RESULTS}/go-test-report.xml
          go tool cover -html=/tmp/cover.out -o /tmp/cover.html
      - store_artifacts:
          path: /tmp/cover.html
          destination: coverage
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build:
    jobs:
      - build:
          name: build
